### PR TITLE
No expect of EAGAIN from sysread

### PR DESCRIPTION
**Pull request by sorah**

### CODE REVIEW

**Comment by sorah** [comment]
oops, submitted without writing description. `IO#sysread` doesn't raise `Errno::EAGAIN`, because it's a blocking method. This `sysread` loop could infinitely get blocked, so remove the loop and use select(2) every time to check fd states.

**Comment by k0kubun** [comment]
Errno::EAGAIN was originally for read_nonblock https://github.com/k0kubun/mruby-open3/pull/7. And I agree that now the rescue is obsolete and loop should be omitted. Thanks.

**Comment by sorah** [comment]
oh, I see.

@eagletmt let me know if I miss something concerns.

**Comment by eagletmt** [comment]
LGTM

**Pull request merged**
